title: Ansible Automation Platform Troubleshooting Guide
description: A basic guide to Ansible Automation Platform troubleshooting

remote_theme: clearpathrobotics/jekyll-rtd-theme

defaults:
  - scope:
      path: "README.md"
    values:
      permalink: "index.html"
